export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  Auth: { mode: 'signup' | 'login' };
  AccountRecovery: undefined;
  PersonaSelection: undefined;
  InterestPicker: undefined;
  Main: undefined;
  ArticleReader: { articleId: string };
  Paywall: undefined;
  Search: undefined;
  Notifications: undefined;
  NotificationPreferences: undefined;
  Newsletters: undefined;
  SubscriptionPlans: undefined;
  ManageSubscription: undefined;
  BillingHistory: undefined;
  Saved: undefined;
  Downloads: undefined;
  ReadingHistory: undefined;
  Profile: undefined;
  AccountSecurity: undefined;
  FeedSettings: undefined;
  Accessibility: undefined;
  DataOffline: undefined;
  EditionRegion: undefined;
  EditorialStandards: undefined;
  Corrections: undefined;
  HelpCenter: undefined;
  PrivacyTerms: undefined;
  About: undefined;
  SectionFeed: { section: string };
  ColumnistPage: { authorId: string };
  TodaysPaper: undefined;
  BreakingNews: undefined;
  GamePlay: { gameId: string };
  Watchlist: undefined;
  GiftArticle: { articleId: string };
  You: undefined;
  Language: undefined;
};

export type MainTabParamList = {
  Today: undefined;
  Explore: undefined;
  WatchListen: undefined;
  Games: undefined;
  Markets: undefined;
};
