import type { NavigatorScreenParams } from '@react-navigation/native';

export type RootStackParamList = {
  Splash: undefined;
  Onboarding: undefined;
  Auth: { mode: 'signup' | 'login' };
  AccountRecovery: undefined;
  PersonaSelection: undefined;
  InterestPicker: undefined;
  Main: NavigatorScreenParams<MainTabParamList> | undefined;
  ArticleReader: { articleId: string };
  Paywall: undefined;
  Search: undefined;
  Notifications: undefined;
  NotificationPreferences: undefined;
  Interests: undefined;
  Referrals: undefined;
  CommentNotifications: undefined;
  SubscriptionPlans: undefined;
  ManageSubscription: undefined;
  BillingHistory: undefined;
  Profile: undefined;
  AccountSecurity: undefined;
  FeedSettings: undefined;
  Accessibility: undefined;
  DataOffline: undefined;
  EditionRegion: undefined;
  EditorialStandards: undefined;
  Corrections: undefined;
  HelpCenter: undefined;
  PrivacyTerms: undefined;
  About: undefined;
  SectionFeed: { section: string };
  ColumnistPage: { authorId: string };
  TodaysPaper: undefined;
  BreakingNews: undefined;
  GamePlay: { gameId: string };
  Markets: undefined;
  MarketDetail: { symbol: string };
  NewsletterIssue: { newsletterId: string };
  Watchlist: undefined;
  Settings: undefined;
  Language: undefined;
};

export type MainTabParamList = {
  Home: undefined;
  WatchListen: undefined;
  Games: undefined;
  Latest: undefined;
  ForYou: undefined;
};
